# This file should stay pretty static.
# The 'version' is updated when the package is created.
# See release.mk - build/helm target.
apiVersion: v2
name: coder
description: Run Coder in Kubernetes
type: application
version: 1.0.0
home: https://coder.com
sources:
  - https://github.com/cdr/enterprise-helm
icon: https://helm.coder.com/coder_logo_blue.png
maintainers:
  - name: Coder Engineering
    email: helm@coder.com

dependencies:
- name: ingress-nginx
  version: "~3.23.0"
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: ingress.useDefault
