# serviceType -- See the following for the different serviceType options and
# their use:
# https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
serviceType: "ClusterIP"

# podSecurityPolicyName -- The name of the pod security policy to apply to all
# Coder services and user environments. The optional ingress has its own field
# for pod security policy as well.
podSecurityPolicyName: ""

# clusterDomainSuffix -- If you've set a custom default domain for your
# cluster, you may need to remove or change this DNS suffix for service
# resolution to work correctly.
clusterDomainSuffix: ".svc.cluster.local"

# imagePullPolicy -- Sets the policy for pulling a container image across all
# services.
imagePullPolicy: Always

# contains configuration for the bundled ingress controller.
ingress:
  # ingress.useDefault -- If set to true will deploy an nginx ingress that will
  # allow you to access Coder from an external IP address, but if your
  # kubernetes cluster is configured to provision external IP addresses. If you
  # would like to bring your own ingress and hook Coder into that instead, set
  # this value to false.
  useDefault: true
  # ingress.host -- The hostname to use for accessing the platform. This can
  # be left blank and the user can still access the platform from the external
  # IP or a DNS name that resolves to the external IP address.
  host: ""
  # ingress.podSecurityPolicyName -- The name of the pod security policy the
  # built in ingress controller should abide. It should be noted that the
  # ingress controller requires the `NET_BIND_SERVICE` capability, privilege
  # escalation, and access to privileged ports to successfully deploy.
  podSecurityPolicyName: ""
  # ingress.additionalAnnotations -- Additional annotations to be used when
  # creating the ingress. These only apply to the Ingress Kubernetes kind.
  # The annotations can be used to specify certificate issuers or
  # other cloud provider specific integrations. Annotations are provided as
  # strings e.g. [ "mykey:myvalue", "mykey2:myvalue2" ] 
  additionalAnnotations: []
  # ingress.tls -- TLS options for the ingress. The hosts used for the tls
  # configuration come from the ingress.host and the devurls.host variables. If
  # those don't exist, then the TLS configuration will be ignored.
  tls:
    # ingress.tls.enable -- Enables the tls configuration.
    enable: false
    # ingress.tls.hostSecretName -- The secret to use for the ingress.host
    # hostname.
    hostSecretName: ""
    # ingress.tls.devurlsHostSecretName -- The secret to use for the
    # devurls.host hostname.
    devurlsHostSecretName: ""
  # ingress.service -- Options related to the ingress Kubernetes Service object.
  service:
    # ingress.service.annotations -- Additional annotations to add to the Service
    # object. For example to make the ingress spawn an internal load balancer:
    # annotations:
    #  cloud.google.com/load-balancer-type: "Internal" 
    annotations: {}

devurls:
  # devurls.host -- Should be a wildcard hostname to allow matching against
  # custom-created dev URLs. Leaving as an empty string results in devurls
  # being disabled. Example: "*.devurls.coder.com".
  host: ""
  sslMode: "require"

# envproxy contains configuration for the service handling long-lived
# connections to environments such as IDE or shell sessions.
envproxy:
  # envproxy.accessURL -- The URL reported to cemanager. Must be accessible by
  # cemanager and all users who can use this workspace provider. Derived from
  # ingress.host if not set. This should be a full URL, complete with protocol
  # and trailing "/ingress" (no trailing slash).
  accessURL: ""
  # envproxy.replicas -- The number of replicas to run of the envproxy.
  replicas: 1
  # envproxy.image -- Injected during releases.
  image: ""
  # envproxy.resources -- Kubernetes resource request and limits for envproxy
  # pods.
  # To unset a value, set it to "".
  # To unset all values, you can provide a values.yaml file which sets resources
  # to nil. See values.yaml for an example.
  #
  # e.g:
  # envproxy:
  #   # This will cause all values to be unset.
  #   resources:
  #   replica: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
  # envproxy.terminationGracePeriodSeconds -- Amount of seconds to wait before
  # shutting down the environment proxy if there are still open connections.
  # This is set very long intentionally so developers do not deal with
  # disconnects during deployments.
  terminationGracePeriodSeconds: 14400

# cemanager -- Details for connecting to the cemanager instance.
# NOTE: the envproxy must be accessible by envproxy.accessURL from the
# cemanager.
cemanager:
  # cemangaer.accessURL -- The access URL from envproxy to cemanager.
  accessURL: ""
  # cemanager.token -- Set by coder-cli during the initial installation.
  token: ""

# certs -- Describes CAs that should be added to Coder services. These certs
# are NOT added to environments.
certs:
  secret:
    # certs.secret.name -- The name of the secret.
    name: ""
    # certs.secret.key -- The key in the secret pointing to the certificate
    # bundle.
    key: ""

# namespaceWhitelist -- A list of additional namespaces that environments may
# be deploy to.
# NOTE: this only applies to environments managed by this workspace provider.
namespaceWhitelist: []

ssh:
  # ssh.enable -- Enables accessing environments via SSH.
  # NOTE: this only applies to environments managed by this workspace provider.
  enable: true

# serviceTolerations -- Tolerations are applied to all Coder managed services.
# Each element is a toleration object. To set user environment tolerations see
# environments.tolerations. See values.yaml for an example.
#
# e.g.
# serviceTolerations:
# - key: "my key"
#   operator: "Exists"
#   effect: "NoExecute"
#   tolerationSeconds: 6000
serviceTolerations: []

# logging configures the logging format of Coder services
logging:
  # logging.human -- Where to send logs that are formatted for readability by a
  # human. Set to an empty string to disable.
  human: /dev/stderr
  # logging.stackdriver -- Where to send logs that are formatted for Google
  # Stackdriver. Set to an empty string to disable.
  stackdriver: ""
  # logging.json -- Where to send logs that are formatted as JSON. Set to an
  # empty string to disable.
  json: ""
