coderd:
  serviceSpec:
    type: ClusterIP
  replicas: 1
  turn:
    enable: true
  podSecurityContext:
    readOnlyRootFilesystem: true
    runAsUser: null
    seccompProfile: null
  securityContext:
    readOnlyRootFilesystem: true
    seccompProfile: null

postgres:
  default:
    resources:
      requests:
        cpu: "0m"
        memory: "32Mi"
