---
# The service account used by environments. It has no permissions and is only 
# used to bind a pod security policy (if one is provided).
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  # This name is includes the release name to avoid overlapping with deprecated
  # namespaceWhitelist-era service accounts from the built-in workspace
  # provider.
  name: {{ include "coder.environments.saName" . | quote }}
{{- include "coder.environments.configMap" . }}
